Повторый пул реквест
js-tasks-ru/jsbasic-20231109_igor-illarionov89 pull request #2
Opened 2023-11-16 12:43 UTC by Igor-Illarionov

2023-11-16 12:44 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-16 14:06 UTC, SinimaWath requested changes

2023-11-16 14:06 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Так как результут операции boolean, нет необходимости в `if`:
`return strToLowerCase.includes('1xbet') ||  strToLowerCase.includes('xxx')`

2023-11-16 14:06 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Тут можно упростить без if, если привести `name` к boolean:
`return Boolean(name) && name.length >= 4 && !name.includes(' ')`

2023-11-17 13:37 UTC, Igor-Illarionov commented on 1-module/4-task/index.js
> +  return false;
Понял. Спасибо большое! Исправил. Пришлю. Вчера на уроке как раз объясняли этот момент.

2023-11-17 13:45 UTC, Igor-Illarionov commented on 1-module/2-task/index.js
> +  }
Спасибо за обратную связь! Исправил

2023-11-17 13:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-17 16:04 UTC, SinimaWath approved these changes

2023-11-17 16:05 UTC, merged