Решил все задачи по теме: Функции и массивы
js-tasks-ru/jsbasic-20231109_igor-illarionov89 pull request #4
Opened 2023-11-27 05:25 UTC by Igor-Illarionov

2023-11-27 05:26 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-28 18:47 UTC, SinimaWath requested changes

2023-11-28 18:47 UTC, SinimaWath commented on 3-module/1-task/index.js
> +return userNames;
тут надо заиспользовать: `users.map(...)`

2023-11-28 18:47 UTC, SinimaWath commented on 3-module/4-task/index.js
> +return stringUserBalance;
Давай весь этот сложный код заменим на несколько строчек:
```
return users
   .filter(...)
   .map(...)
   .join('\n')
```

2023-11-28 18:47 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return result;
нет необходимости делать временный обьект:
```
return {
  min: ....
  max: ....
}
```

2023-12-02 06:54 UTC, Igor-Illarionov commented on 3-module/5-task/index.js
> +  return result;
Спасибо за ответы! Отправлю исправленный вариант

2023-12-02 07:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-12-02 07:10 UTC, Igor-Illarionov commented on 3-module/5-task/index.js
> +  return result;
Готово

2023-12-03 18:10 UTC, SinimaWath approved these changes

2023-12-03 18:11 UTC, merged